import { test, expect } from "@playwright/test";
import { createRequire } from "node:module";
import { mkdirSync } from "node:fs";
import { salesFixture } from "./helpers/sales-fixture";
import { deriveSalesRegister } from "../src/lib/sales/register";
const requireFixture = createRequire(__filename);
const { reservationRouteFixture } = requireFixture("./helpers/reservation-route-fixture.mjs");
const { fixture } = requireFixture("./helpers/dashboard-fixture.mjs");
const evidence = "docs/sales-corrections/screenshots";
test.beforeAll(() => mkdirSync(evidence, { recursive: true }));

test("authorised agent creates a draft, resumes, uploads, submits, corrects a return and receives developer approval", async ({ page }) => {
  const f = await salesFixture(page);
  f.profile.role = "sales_agent"; f.profile.organisation_id = "agent-org" as never;
  f.rows.unit_sale_attempts = [{ ...f.attempt, id: "historic", is_active: false, workflow_status: "fallen_through", buyer_name: "Historic buyer", attempt_number: 1 }];
  f.rows.buildings[0].sales_agent_organisation_id = "agent-org";
  f.rows.organisations = [{ id: "agent-org", name: "Synthetic Agency", type: "sales_agent" }];
  const backend = reservationRouteFixture(f.rows, f.profile);
  await page.route("**/api/sales/reservations", async route => {
    const request = route.request();
    const response = await backend.handler(new Request(request.url(), { method: request.method(), headers: request.headers(), body: new Uint8Array(request.postDataBuffer() ?? []) }));
    await route.fulfill({ status: response.status, contentType: "application/json", body: await response.text() });
  });
  const snapshot = () => deriveSalesRegister(fixture({ viewer: f.profile, buildings: f.rows.buildings, units: f.rows.units, sales: f.rows.unit_sale_attempts, organisations: f.rows.organisations }));
  await page.reload();
  await expect(page.getByLabel("Personal buyer name")).toBeVisible();
  await expect(page.getByRole("button", { name: "Submit reservation", exact: true })).toBeDisabled();
  await page.getByLabel("Personal buyer name").fill("Synthetic New Buyer");
  const requests: string[] = []; page.on("request", request => requests.push(new URL(request.url()).pathname));
  await page.getByRole("button", { name: "Save draft", exact: true }).click();
  await expect(page.getByText(/Reservation draft saved for Unit/)).toBeVisible();
  await expect(page.getByRole("button", { name: "Save draft", exact: true })).toBeEnabled();
  const draft = f.rows.unit_sale_attempts.find(row => row.is_active)!;
  expect(draft.workflow_status).toBe("draft"); expect(snapshot().rows[0].actions[0].party.label).toBe("Synthetic Agency");
  expect(requests.some(path => /snags|tenancies|building_sale_defaults/.test(path))).toBe(false);
  await page.getByRole("button", { name: /Back to sales overview/ }).click();
  await page.getByRole("cell", { name: "Unit 101", exact: true }).click();
  await page.reload();
  await expect(page.getByLabel("Personal buyer name")).toHaveValue("Synthetic New Buyer");
  await page.getByLabel("Buyer email", { exact: true }).fill("buyer@example.test");
  await page.getByLabel("Buyer phone", { exact: true }).fill("07000000000");
  await page.getByLabel("Buyer solicitor", { exact: true }).fill("Buyer Solicitors Ltd");
  await page.getByLabel("Reservation date", { exact: true }).fill("2026-08-01");
  await page.getByRole("checkbox", { name: /I have checked that the reservation form/ }).check();
  await page.getByRole("button", { name: "Submit reservation", exact: true }).click();
  await expect(page.getByText("Upload the reservation form PDF before submitting the reservation.", { exact: true })).toBeVisible();
  expect(draft.workflow_status).toBe("draft");
  await page.locator('input[type="file"]').setInputFiles({ name: "synthetic-reservation.pdf", mimeType: "application/pdf", buffer: Buffer.from("%PDF-1.4\nSynthetic reservation test") });
  await expect(page.getByText("Upload the reservation form PDF before submitting the reservation.", { exact: true })).toBeHidden({ timeout: 15_000 });
  await page.locator("#sales-stage-reservation").screenshot({ path: `${evidence}/agent-reservation-entry.png` });
  await page.getByRole("button", { name: "Submit reservation", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Submitted reservation pack" })).toBeVisible();
  expect(draft.workflow_status).toBe("awaiting_approval"); expect(snapshot().rows[0].actions[0].party.kind).toBe("developer");
  await expect(page.getByRole("button", { name: "Approve reservation", exact: true })).toHaveCount(0);
  f.profile.role = "developer"; await page.reload();
  await page.getByRole("button", { name: "Reject reservation", exact: true }).click();
  await page.getByLabel("Rejection reason", { exact: true }).fill("Correct the buyer name");
  await page.getByRole("button", { name: "Confirm rejection", exact: true }).click();
  await expect(page.getByRole("button", { name: "Resubmit reservation", exact: true })).toBeVisible();
  expect(snapshot().rows[0].actions[0].party.label).toBe("Synthetic Agency");
  f.profile.role = "sales_agent"; await page.reload();
  await page.getByLabel("Personal buyer name").fill("Corrected Synthetic Buyer");
  await page.getByRole("checkbox", { name: /I have checked that the reservation form/ }).check();
  await page.getByRole("button", { name: "Resubmit reservation", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Submitted reservation pack" })).toBeVisible();
  f.profile.role = "developer"; await page.reload();
  await page.getByRole("button", { name: "Approve reservation", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Approval record", exact: true })).toBeVisible();
  expect(f.unit.sale_status).toBe("reserved"); expect(draft.workflow_status).toBe("approved");
  expect(f.rows.unit_sale_attempts.find(row => row.id === "historic")?.buyer_name).toBe("Historic buyer");
  expect(f.rows.unit_sale_attempts).toHaveLength(2); expect(backend.uploads).toHaveLength(1);
});

test("building seller conveyancer, single return control and read-only reservation guidance", async ({ page }) => {
  const f = await salesFixture(page);
  f.profile.role = "conveyancer"; f.profile.organisation_id = "legal-org" as never;
  f.rows.buildings[0].conveyancer_organisation_id = "legal-org";
  f.rows.buildings[0].sales_agent_organisation_id = "agent-org";
  f.rows.organisations = [{ id: "legal-org", name: "Synthetic Seller Legal", type: "conveyancer" }, { id: "agent-org", name: "Synthetic Agency", type: "sales_agent" }];
  Object.assign(f.attempt, { conveyancer_organisation_id: null, workflow_status: "approved", reservation_approved_at: "2026-08-01", commercial_approved_at: "2026-08-01", buyer_solicitor_name: "Unrelated Buyer Solicitors" });
  f.unit.sale_status = "reserved";
  await page.route("**/api/sales/register?*", route => route.fulfill({ json: deriveSalesRegister(fixture({ buildingId: String(f.unit.building_id), viewer: f.profile, buildings: f.rows.buildings, units: f.rows.units, sales: [f.attempt], organisations: f.rows.organisations })) }));
  await page.goto(`/?screen=sales&building=${f.unit.building_id}`);
  await expect(page.getByRole("table")).toContainText("Synthetic Seller Legal");
  await page.getByLabel("Search", { exact: true }).fill("101");
  await page.getByLabel("Stage", { exact: true }).selectOption("reserved");
  await page.getByLabel("Action with", { exact: true }).selectOption("ours");
  await page.screenshot({ path: `${evidence}/configured-conveyancer.png`, fullPage: true });
  await page.getByRole("link", { name: "Unit 101", exact: true }).click();
  await expect(page.getByRole("button", { name: /Back to sales overview/ })).toHaveCount(1);
  await expect(page.getByRole("link", { name: "Back to Sales", exact: true })).toHaveCount(0);
  await page.screenshot({ path: `${evidence}/single-return-control.png`, fullPage: true });
  await page.getByRole("button", { name: /Back to sales overview/ }).click();
  await expect(page.getByLabel("Search", { exact: true })).toHaveValue("101");
  await expect(page.getByLabel("Stage", { exact: true })).toHaveValue("reserved");
  await expect(page.getByLabel("Action with", { exact: true })).toHaveValue("ours");
  await expect(page).toHaveURL(new RegExp(`building=${f.unit.building_id}`));
  Object.assign(f.attempt, { workflow_status: "draft", reservation_approved_at: null, commercial_approved_at: null }); f.unit.sale_status = "for_sale";
  await page.goto(`/?screen=sales&building=${f.unit.building_id}&salesUnitId=${f.unit.id}`);
  await expect(page.getByText("Awaiting Synthetic Agency to record the reservation.", { exact: true })).toBeVisible();
  await expect(page.getByLabel("Personal buyer name")).toHaveCount(0);
  await expect(page.getByRole("button", { name: /^(Save draft|Submit reservation|Approve reservation)$/ })).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Record reservation", exact: true })).toHaveCount(0);
  await page.locator("#sales-stage-reservation").screenshot({ path: `${evidence}/conveyancer-read-only.png` });
});

for (const role of ["admin", "developer", "sales_agent"]) test(`${role} has one working overview button on direct entry without unrelated reloads`, async ({ page }) => {
  const f = await salesFixture(page); f.profile.role = role; await page.reload();
  await expect(page.getByRole("button", { name: "Save draft", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: /Back to sales overview/ })).toHaveCount(1);
  const paths: string[] = []; page.on("request", request => paths.push(new URL(request.url()).pathname));
  await page.getByRole("button", { name: /Back to sales overview/ }).click();
  await expect(page).not.toHaveURL(/salesUnitId=/);
  await expect(page).toHaveURL(new RegExp(`building=${f.unit.building_id}`));
  await page.waitForLoadState("networkidle");
  expect(paths.some(path => /snags|tenancies|user_building_access/.test(path))).toBe(false);
});
