import { expect, test, type Page } from "@playwright/test";
import { salesFixture as fixture, userId, at } from "./helpers/sales-fixture";

async function expectSteps(page: Page, stage: string, labels: string[]) {
  const cards = page.getByRole("list", { name: `${stage} tasks`, exact: true }).getByRole("listitem");
  await expect(cards).toHaveCount(labels.length);
  for (const [index, label] of labels.entries()) await expect(cards.nth(index).getByText(label, { exact: true })).toBeVisible();
}

test("reservation and exchange show their saved milestones, rejection and completed history", async ({ page }) => {
  const f = await fixture(page);
  await expectSteps(page, "Reservation", ["Current", "Locked"]);
  await expect(page.locator("#sales-stage-reservation").getByRole("heading", { name: "Record reservation", exact: true })).toBeVisible();
  f.attempt.workflow_status = "awaiting_approval";
  f.attempt.reservation_submitted_at = at(1);
  f.attempt.reservation_submitted_by_user_id = userId;
  await f.reloadStage("Reservation");
  await expectSteps(page, "Reservation", ["Complete", "Current"]);
  await expect(page.getByRole("list", { name: "Reservation tasks" })).toContainText(`by ${f.profile.full_name}`);
  f.attempt.workflow_status = "rejected";
  f.attempt.reservation_rejection_reason = "Correct the buyer details.";
  f.attempt.reservation_rejected_at = at(2);
  await f.reloadStage("Reservation");
  await expectSteps(page, "Reservation", ["Changes required", "Locked"]);
  await expect(page.getByText("Correct the buyer details.", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Resubmit reservation" })).toBeVisible();
  f.attempt.workflow_status = "approved";
  f.attempt.reservation_approved_at = at(3);
  f.attempt.reservation_approved_by_user_id = userId;
  f.unit.sale_status = "reserved";
  await f.reloadStage("Reservation");
  await expectSteps(page, "Reservation", ["Complete", "Complete"]);
  await expect(page.getByRole("list", { name: "Reservation tasks" }).getByText(`by ${f.profile.full_name}`, { exact: true })).toHaveCount(2);
  await expect(page.getByRole("heading", { name: "Approval record", exact: true })).toBeVisible();
  await f.reloadStage("Exchange");
  await expectSteps(page, "Exchange", ["Current", "Locked"]);
  f.attempt.workflow_status = "ready_for_exchange";
  f.attempt.commercial_approved_at = at(3);
  await f.reloadStage("Exchange");
  await expectSteps(page, "Exchange", ["Complete", "Current"]);
  f.attempt.workflow_status = "exchanged";
  f.attempt.exchanged_at = "2026-08-04";
  f.unit.sale_status = "exchanged";
  await f.reloadStage("Exchange");
  await expectSteps(page, "Exchange", ["Complete", "Complete"]);
});

test("completion survives reload through upload, query, replacement, approval and recording", async ({ page }) => {
  const f = await fixture(page);
  f.unit.sale_status = "exchanged";
  f.attempt.workflow_status = "exchanged";
  f.attempt.exchanged_at = "2026-08-01";
  await f.reloadStage("Completion");
  await expectSteps(page, "Completion", ["Current", "Locked", "Locked"]);
  f.documents();
  const second = f.rows.unit_sale_document_versions.pop()!;
  await f.reloadStage("Completion");
  await expectSteps(page, "Completion", ["Current", "Locked", "Locked"]);
  f.rows.unit_sale_document_versions.push(second);
  await f.reloadStage("Completion");
  await expectSteps(page, "Completion", ["Complete", "Current", "Locked"]);
  await expect(page.getByRole("button", { name: "Approve completion documents", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Reject / query documents", exact: true })).toBeDisabled();
  await page.getByLabel("Rejection / query reason").fill("Correct the completion balance.");
  await expect(page.getByRole("button", { name: "Reject / query documents", exact: true })).toBeEnabled();
  await expect(page.getByRole("button", { name: "Mark unit Completed" })).toHaveCount(0);
  f.rows.unit_sale_documents.forEach((doc) => Object.assign(doc, { status: "query_raised", query_note: "Correct the completion balance.", updated_at: at(3) }));
  f.rows.unit_sale_workflow_events.push(f.event("completion_documents_query_raised", 3, { queryNote: "Correct the completion balance." }));
  f.profile.role = "conveyancer";
  await f.reloadStage("Completion");
  await expectSteps(page, "Completion", ["Changes required", "Awaiting resubmission", "Locked"]);
  await expect(page.getByText("Correct the completion balance.", { exact: true }).first()).toBeVisible();
  await expect(page.getByRole("button", { name: "Upload completion statement", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Approve completion documents" })).toHaveCount(0);
  Object.assign(f.rows.unit_sale_documents[0], { status: "uploaded", query_note: null, updated_at: at(4) });
  f.rows.unit_sale_document_versions[0].is_current = false;
  f.rows.unit_sale_document_versions.push({ ...f.rows.unit_sale_document_versions[0], id: "replacement", is_current: true, version_number: 2, uploaded_at: at(4) });
  await f.reloadStage("Completion");
  await expectSteps(page, "Completion", ["Complete", "Current", "Locked"]);
  await expect(page.getByRole("heading", { name: "Documents resubmitted for review" })).toBeVisible();
  f.rows.unit_sale_documents.forEach((doc) => Object.assign(doc, { status: "approved", approved_at: at(5), approved_by_user_id: userId, query_note: null }));
  f.rows.unit_sale_workflow_events.push(f.event("completion_documents_approved", 5));
  f.attempt.workflow_status = "completion_pending";
  await f.reloadStage("Completion");
  await expectSteps(page, "Completion", ["Complete", "Complete", "Current"]);
  await page.getByLabel("Actual completion date", { exact: true }).fill("2026-08-06");
  await expectSteps(page, "Completion", ["Complete", "Complete", "Current"]);
  await expect(page.getByRole("button", { name: "Mark unit Completed" })).toBeEnabled();
  f.attempt.workflow_status = "completed";
  f.attempt.completed_at = "2026-08-06";
  f.unit.sale_status = "completed";
  f.rows.unit_sale_workflow_events.push(f.event("completion_recorded", 6));
  await f.reloadStage("Completion");
  await expectSteps(page, "Completion", ["Complete", "Complete", "Complete"]);
  await expect(page.getByRole("heading", { name: "Completion recorded", exact: true })).toBeVisible();
  await page.getByRole("button", { name: /^Comments/ }).first().click();
  await page.locator('#sale-conversation').getByRole("tab", { name: "Activity", exact: true }).click();
  await expect(page.getByText("Reason: Correct the completion balance.", { exact: true })).toBeVisible();
});

test("task cards use available width without overflow at desktop, tablet and mobile sizes", async ({ page }, testInfo) => {
  const f = await fixture(page);
  f.documents();
  f.attempt.workflow_status = "completed";
  f.attempt.exchanged_at = "2026-08-01";
  f.attempt.completed_at = "2026-08-06";
  f.unit.sale_status = "completed";
  f.rows.unit_sale_documents.forEach((doc) => Object.assign(doc, { status: "approved", approved_at: at(5), approved_by_user_id: userId }));
  f.rows.unit_sale_workflow_events.push(f.event("completion_recorded", 6));
  await f.reloadStage("Completion");
  for (const width of [1440, 1100, 768, 390]) {
    await page.setViewportSize({ width, height: 1000 });
    const list = page.getByRole("list", { name: "Completion tasks", exact: true });
    await list.scrollIntoViewIfNeeded();
    const box = await list.boundingBox();
    const cards = await list.getByRole("listitem").all();
    const bounds = await Promise.all(cards.map((card) => card.boundingBox()));
    const columns = box!.width >= 768 ? 3 : box!.width >= 480 ? 2 : 1;
    expect(Math.abs(bounds[0]!.y - bounds[1]!.y) < 2).toBe(columns > 1);
    expect(Math.abs(bounds[0]!.y - bounds[2]!.y) < 2).toBe(columns === 3);
    for (const card of cards) expect(await card.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
    expect(await page.locator("#sales-stage-completion").evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
    const overflow = await page.evaluate(() => [...document.querySelectorAll("body *")].filter((element) => {
      const bounds = element.getBoundingClientRect();
      return bounds.width > 0 && bounds.right > window.innerWidth + 1 && getComputedStyle(element).position !== "fixed";
    }).slice(-12).map((element) => ({ tag: element.tagName, class: element.className, text: element.textContent?.slice(0, 70), width: element.getBoundingClientRect().width })));
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), JSON.stringify(overflow)).toBe(true);
    await page.locator("#sales-stage-completion").screenshot({ path: testInfo.outputPath(`completion-${width}.png`) });
  }
});
